name: wmsflutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shimmer: ^3.0.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  pluto_grid: ^7.0.2
  qr_flutter: ^4.1.0
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  signature: ^5.4.0
  auto_route: ^7.8.0
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.3.0
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  fonts:
    - family: ABeeZee     
      fonts:
        - asset: assets/fonts/ABeeZee-Regular.ttf
        - asset: assets/fonts/ABeeZee-Italic.ttf
          style: italic
        
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - assets/images/background/

